CREATE TABLE items(id INTEGER PRIMARY KEY, name TEXT, amount INTEGER, price REAL, color TEXT);
INSERT INTO items VALUES(1, "Tshirt", 100, 25, "Red");
INSERT INTO items VALUES(2, "Tshirt", 100, 25, "Blue");
INSERT INTO items VALUES(3, "Tshirt", 100, 25, "Black");
INSERT INTO items VALUES(4, "Hat", 25, 5, "White");
INSERT INTO items VALUES(5, "Hat", 23, 5, "Brown");
INSERT INTO items VALUES(6, "Skirt", 100, 30.4, "Red");
INSERT INTO items VALUES(7, "Skirt", 150, 20.5, "Green");
INSERT INTO items VALUES(8, "Jumper", 100, 45, "Brown");
INSERT INTO items VALUES(9, "Jumper", 100, 45, "Black");
INSERT INTO items VALUES(10, "Jumper", 100, 45, "Blue");
INSERT INTO items VALUES(11, "Hoodie", 75, 55, "Red");
INSERT INTO items VALUES(12, "Hoodie", 100, 55, "Violet");
INSERT INTO items VALUES(13, "Hoodie", 100, 55, "Pink");
INSERT INTO items VALUES(14, "High heels", 50, 35, "Black");
INSERT INTO items VALUES(15, "High heels", 100, 33.5, "Red");
SELECT * FROM items ORDER BY price;
SELECT name, SUM(price) FROM items GROUP BY name ORDER BY price;
SELECT name, SUM(amount) FROM items GROUP BY name ORDER BY amount;
